name: Generate rule-sets
on:
  workflow_dispatch:
  schedule:
    - cron: "5 3 * * *" # 7:00 AM UTC+8 (use "00 00 * * *" for 8:00 AM UTC+8)

permissions:
  contents: write

jobs:
  generate_rule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Download rulesets
        run: |
          curl -fSL --parallel --parallel-immediate \
            -o "geolocation-!cn.json" https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/geolocation-!cn.json \
            -o geoip-cn.txt https://cdn.jsdelivr.net/gh/1715173329/IPCIDR-CHINA@master/ip.txt \
            -o netflix.json https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/netflix.json

      - name: Generate second-last-rule.json
        run: |
          jq -Rn --slurpfile a "geolocation-!cn.json" '{
            version: 1,
            rules: [{
              type: "logical",
              mode: "and",
              rules: [
                {
                  domain: $a[0].rules[0].domain,
                  invert: true
                },
                {
                  ip_cidr: [inputs | select(length > 0)]
                }
              ]
            }]
          }' geoip-cn.txt > second-last-rule.json

      - name: Generate netflix-ipv6.txt
        run: |
          jq -r '.rules[0].ip_cidr[] | select(contains(":"))' netflix.json > netflix-ipv6.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add second-last-rule.json netflix-ipv6.txt
          if git diff --staged --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git commit -m "Released on $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')"
            git push
          fi
